import { AuditParameter } from './models.js';

export const INITIAL_AUDIT_CHECKLIST: AuditParameter[] = [
  // --- CATEGORY 1: ZERO TOLERANCE (Score: 100, Fatal: YES) ---
  {
    id: 'ZTI-001',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Agency Identification: Board, GST Details',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['GST Registration Certificate', 'Agency Identification Board / Details', 'PAN / Incorporation Record'],
    keywords: ['GST', 'GSTIN', 'GST Registration', 'Goods and Services Tax', 'Registration Certificate', 'Agency Identification'],
    logic: 'SINGLE',
    evaluation_rules: ['Check for valid GSTIN or Agency Identification details'],
    enabled: true
  },
  {
    id: 'ZTI-002',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Agency Access Control',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Biometric access log', 'ID Card system configuration', 'Physical access control policy / photos'],
    keywords: ['biometric', 'access control', 'door access', 'badge reader', 'physical security', 'card system'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Distinguish policy from physical/system implementation evidence'],
    enabled: true
  },
  {
    id: 'ZTI-003',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Dedicated workspace/systems for Phone Lending business',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Dedicated workspace documentation', 'System allocation sheet', 'Segregation proof'],
    keywords: ['phone lending', 'dedicated workspace', 'system allocation', 'segregated bay', 'lending desk'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify segregated space/systems dedicated to lending operations'],
    enabled: true
  },
  {
    id: 'ZTI-004',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'DRA Passed / Trained Certificate',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['DRA Certificate', 'DRA Training Completion Certificate', 'Training Record'],
    keywords: ['DRA', 'Debt Recovery Agent', 'DRA Trained', 'DRA Certificate', 'NBFET', 'Training Certificate'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: true,
    evaluation_rules: ['Extract agent name, training status, cert number, issue date, expiry date'],
    enabled: true
  },
  {
    id: 'ZTI-005',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Valid Police Verification (PV) / Applied for',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Police Verification Report', 'Proof of Police Verification Application'],
    keywords: ['police verification', 'character certificate', 'PV report', 'police clearance', 'verification acknowledgement'],
    logic: 'OR',
    requires_validity_check: true,
    expiry_required: true,
    evaluation_rules: ['Distinguish VERIFIED, APPLIED, MISSING, EXPIRED, or UNCLEAR'],
    enabled: true
  },
  {
    id: 'ZTI-006',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Misconduct or another breach of COC',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Disciplinary Log', 'Code of Conduct Breach Report', 'Compliance Declaration'],
    keywords: ['misconduct', 'code of conduct breach', 'disciplinary action', 'compliance violation', 'incident log'],
    logic: 'SINGLE',
    requires_human_review: true,
    evaluation_rules: ['Requires HUMAN REVIEW. Absence of document alone does not guarantee compliance'],
    enabled: true
  },
  {
    id: 'ZTI-007',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Agent Onboarding Documents Authentication',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Agent Onboarding Checklist', 'KYC Authentication Record', 'Approval Form'],
    keywords: ['onboarding checklist', 'agent onboarding', 'KYC verification', 'background check', 'approval record'],
    logic: 'SINGLE',
    evaluation_rules: ['Check onboarding documentation and authenticated KYC records'],
    enabled: true
  },
  {
    id: 'ZTI-008',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Printer/Scanner restricted / USB & Cloud storage access restricted',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Endpoint Security Policy', 'DLP / GPO Configuration Export', 'IT Audit Screenshot'],
    keywords: ['USB restriction', 'cloud storage block', 'printer restricted', 'DLP policy', 'GPO configuration', 'removable media'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Distinguish POLICY_EXISTS from IMPLEMENTATION_EVIDENCE'],
    enabled: true
  },
  {
    id: 'ZTI-009',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Blacklisting of social sites/personal email ID/messaging apps',
    fatal: true,
    severity: 'CRITICAL',
    required_evidence: ['Web Filtering Policy', 'Firewall / Proxy Configuration Export', 'Endpoint Policy'],
    keywords: ['web filtering', 'blacklisting', 'social media block', 'personal email block', 'messaging apps restricted', 'proxy block'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Distinguish policy document from technical implementation evidence'],
    enabled: true
  },
  {
    id: 'ZTI-010',
    category: 'ZERO_TOLERANCE',
    category_name: 'Regulatory and Operational Integrity',
    category_weight: 100,
    parameter: 'Clean desk policy',
    fatal: true,
    severity: 'HIGH',
    required_evidence: ['Clean Desk Policy', 'Inspection Records', 'Audit Photos / Compliance Declarations'],
    keywords: ['clean desk', 'clean desk policy', 'workspace inspection', 'nightly audit', 'compliance declaration'],
    logic: 'SINGLE',
    distinguish_policy: true,
    requires_human_review: true,
    evaluation_rules: ['Do not conclude physical workspace compliance from policy alone'],
    enabled: true
  },

  // --- CATEGORY 2: GOVERNANCE, COMPLIANCE & INFOSEC (Score: 60, Fatal: NO) ---
  {
    id: 'GCI-001',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Valid agency ID Card and Endorsement Card (for Field)',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Agency ID Card Sample/Register', 'Field Endorsement Card'],
    keywords: ['agency ID card', 'endorsement card', 'field agent ID', 'identification card', 'badge issue'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: false,
    evaluation_rules: ['Verify validity and availability of ID and Field Endorsement cards'],
    enabled: true
  },
  {
    id: 'GCI-002',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'ID Deactivation & Agent Termination process',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Termination Policy', 'Deactivation Procedure', 'Agent Deactivation Log'],
    keywords: ['termination process', 'ID deactivation', 'offboarding checklist', 'deactivation log', 'exit process'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Verify deactivation process and actual termination sample records'],
    enabled: true
  },
  {
    id: 'GCI-003',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Agency Staff in appropriate attire',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Dress Code Policy', 'Inspection Reports', 'Workspace Photos'],
    keywords: ['dress code', 'attire policy', 'formal wear', 'inspection report', 'attire review'],
    logic: 'SINGLE',
    requires_human_review: true,
    evaluation_rules: ['Requires HUMAN REVIEW if physical evidence is ambiguous'],
    enabled: true
  },
  {
    id: 'GCI-004',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Refresher trainings conducted; mandatory attendance sheet',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Refresher Training Module', 'Attendance Sheet', 'Training Records'],
    keywords: ['refresher training', 'attendance sheet', 'mandatory training', 'training log', 'participant list'],
    logic: 'SINGLE',
    evaluation_rules: ['Extract training name, date, participants, attendance, trainer, completion status'],
    enabled: true
  },
  {
    id: 'GCI-005',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Agency Performance and Evaluation',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Target vs Actual Report', 'Performance Memos', 'No Dues Certificate (NDC)', 'Asset Management Declaration'],
    keywords: ['target vs actual', 'performance report', 'NDC', 'no dues certificate', 'asset management declaration', 'agency evaluation'],
    logic: 'SINGLE',
    evaluation_rules: ['Check performance evaluation records and NDC declarations'],
    enabled: true
  },
  {
    id: 'GCI-006',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Snipping Tool & MS Paint disabled',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Endpoint Security Configuration', 'GPO AppLocker / Software Restriction Policy', 'Device Audit Log'],
    keywords: ['snipping tool disabled', 'ms paint disabled', 'screen capture restricted', 'AppLocker policy', 'software restriction policy'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Technical audit configuration required. Policy document alone must NOT pass'],
    enabled: true
  },
  {
    id: 'GCI-007',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Password policy of agencies being followed',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Password Policy Document', 'Active Directory Password Policy Export', 'IAM Compliance Report'],
    keywords: ['password policy', 'complexity requirements', 'password expiration', 'Active Directory GPO', 'IAM policy'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Verify policy document and Active Directory / GPO configuration proof'],
    enabled: true
  },
  {
    id: 'GCI-008',
    category: 'GOVERNANCE_COMPLIANCE_INFOSEC',
    category_name: 'Governance, Compliance & INFOSEC',
    category_weight: 60,
    parameter: 'Updated Windows OS',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Patch Compliance Report', 'Endpoint Inventory Export', 'Windows Version / Build Log'],
    keywords: ['windows update', 'patch compliance', 'OS version', 'build number', 'WSUS report', 'endpoint inventory'],
    logic: 'SINGLE',
    evaluation_rules: ['Analyze endpoint OS versions/builds against current patch baseline'],
    enabled: true
  },

  // --- CATEGORY 3: INFRASTRUCTURE & PROCESS MANAGEMENT (Score: 40, Fatal: NO) ---
  {
    id: 'IPM-001',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'PF & ESIC Registration Certificate OR Principal Employer Registration Certificate',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['PF Registration Certificate', 'ESIC Registration Certificate', 'Principal Employer Registration Certificate'],
    keywords: ['PF registration', 'provident fund', 'ESIC certificate', 'principal employer', 'EPFO registration'],
    logic: 'OR',
    evaluation_rules: ['PASS if valid evidence for PF & ESIC OR Principal Employer Certificate exists'],
    enabled: true
  },
  {
    id: 'IPM-002',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'HR & Anti-Sexual Harassment Policy',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['HR Policy', 'POSH Policy Document', 'Employee Handbook'],
    keywords: ['HR policy', 'POSH policy', 'sexual harassment', 'employee handbook', 'ICC committee'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Verify policy existence, version, effective date, and approval status'],
    enabled: true
  },
  {
    id: 'IPM-003',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Rent or Lease Agreement for agency premises & Shops and Establishment Certificate',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Rent / Lease Agreement', 'Shops and Establishment Certificate'],
    keywords: ['rent agreement', 'lease agreement', 'shops and establishment', 'premises agreement', 'commercial lease'],
    logic: 'AND',
    sub_controls: ['RENT_LEASE_AGREEMENT', 'SHOPS_ESTABLISHMENT_CERTIFICATE'],
    evaluation_rules: ['Only PASS when BOTH Rent/Lease Agreement AND Shops & Establishment Certificate exist'],
    enabled: true
  },
  {
    id: 'IPM-004',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Commercial General Liability Insurance (Telecalling Agency)',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['Commercial General Liability Insurance Policy'],
    keywords: ['commercial general liability', 'CGL policy', 'insurance policy', 'liability coverage', 'indemnity insurance'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: true,
    evaluation_rules: ['Extract policy number, insured org, coverage amount, start date, expiry date, insurer. Check validity vs audit date'],
    enabled: true
  },
  {
    id: 'IPM-005',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Visitor register maintained by the agency',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Visitor Register Log', 'Visitor Entry Register CSV/PDF/Scan'],
    keywords: ['visitor register', 'visitor log', 'guest register', 'visitor entry', 'access log book'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify register records exist for the active audit period'],
    enabled: true
  },
  {
    id: 'IPM-006',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'CCTV installed with recordings retained for minimum 90 days',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['CCTV System Configuration', 'Retention Log / Storage Settings Export', 'CCTV Audit Photos'],
    keywords: ['CCTV', 'surveillance camera', 'recording retention', '90 days retention', 'DVR config', 'NVR retention'],
    logic: 'AND',
    sub_controls: ['CCTV_INSTALLED', 'CCTV_RETENTION_90_DAYS'],
    distinguish_policy: true,
    evaluation_rules: ['Compound check: CCTV installed AND storage retention >= 90 days. Policy document alone cannot pass.'],
    enabled: true
  },
  {
    id: 'IPM-007',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Fire Extinguisher available, functional, and not expired',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Fire Extinguisher Inspection Certificate', 'Maintenance Log', 'Inspection Tag Photos'],
    keywords: ['fire extinguisher', 'extinguisher inspection', 'refill date', 'fire safety tag', 'pressure gauge status'],
    logic: 'GROUP',
    sub_controls: ['AVAILABLE', 'FUNCTIONAL', 'NOT_EXPIRED'],
    requires_validity_check: true,
    expiry_required: true,
    evaluation_rules: ['Verify availability, functional status, and unexpired refill date'],
    enabled: true
  },
  {
    id: 'IPM-008',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Fire Drill conducted by the agency (latest one year)',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Fire Drill Report', 'Fire Drill Attendance Record'],
    keywords: ['fire drill', 'evacuation drill', 'mock drill', 'fire drill report', 'fire safety drill'],
    logic: 'SINGLE',
    requires_validity_check: true,
    expiry_required: true,
    evaluation_rules: ['Extract drill date and compare against audit date. FAIL if drill date > 1 year before audit date'],
    enabled: true
  },
  {
    id: 'IPM-009',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Power Backup / Internet Backup / Antivirus on systems',
    fatal: false,
    severity: 'HIGH',
    required_evidence: ['UPS / Generator Maintenance Log', 'Secondary ISP Lease / Config', 'Antivirus Console Report'],
    keywords: ['power backup', 'UPS', 'generator', 'secondary ISP', 'internet backup', 'antivirus', 'endpoint protection', 'EDR'],
    logic: 'GROUP',
    sub_controls: ['POWER_BACKUP', 'INTERNET_BACKUP', 'ANTIVIRUS'],
    evaluation_rules: ['Evaluate three sub-controls individually and return individual evidence status'],
    enabled: true
  },
  {
    id: 'IPM-010',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Business Continuity Plan of the agency',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Business Continuity Plan (BCP) Document', 'Disaster Recovery Plan'],
    keywords: ['business continuity plan', 'BCP', 'disaster recovery', 'DR plan', 'continuity procedure'],
    logic: 'SINGLE',
    distinguish_policy: true,
    evaluation_rules: ['Verify BCP policy existence, approval status, version, and review date'],
    enabled: true
  },
  {
    id: 'IPM-011',
    category: 'INFRASTRUCTURE_PROCESS_MANAGEMENT',
    category_name: 'Infrastructure & Process Management',
    category_weight: 40,
    parameter: 'Escalation Matrix available with Collection agency',
    fatal: false,
    severity: 'MEDIUM',
    required_evidence: ['Escalation Matrix Document', 'Contact Hierarchy Chart'],
    keywords: ['escalation matrix', 'escalation hierarchy', 'contact matrix', 'grievance escalation', 'support contact list'],
    logic: 'SINGLE',
    evaluation_rules: ['Verify presence of structured escalation contact roles and levels'],
    enabled: true
  }
];
